### ISSUE TITLE
Questions about values configurations

### ISSUE THREAD

**Issue by FedericoHeichou** [aescanero/helm-charts#15]
I'm looking the `values.yaml` file and I have many questions (maybe most of them are dumb but please don't blame me).
1. In the rows 21-31 there is:
```yaml
image:
  repository: pschiffe/pdns-mysql
  tag: alpine
  pullPolicy: IfNotPresent
domain: external.local
master: "yes"
api: "yes"
version_string: "anonymous"
default_ttl: "1500"
soa_minimum_ttl: "1200"
default_soa_name: "ns1.external.local"
```
Are they duplicated? 

2. In the docker repository [pschiffe/pdns-mysql](https://hub.docker.com/r/pschiffe/pdns-mysql) is written that pdns come out without mysql server. Why is used 127.0.0.1 as default database in `powerdns` instead of the deployed one (mariadb) with pvc?
3. In `admin` same question as above, why is 127.0.0.1 used for `powerdns_host`? Shouldn't be used the service of powerdns instead? Furthermore in the readme there is `powerdnsadmin.powerdns_host` which is wrong because in the 'values.yaml' the value is (correctly) set to the service (though has a different name but I see in the deploy a `coalesce`)

Yesterday I tried this chart and many errors come out about databases, the admin panel received the error 400 too (I think for wrong host api). This is why today I read the default values in the repo and seems they are wrong.
Furthermore, editing the deployment of powerdns from db host 127.0.0.1 to the service, seems the mariadb was only populated for powerdns-admin and not for powerdns (there wasn't [those default tables](https://doc.powerdns.com/authoritative/guides/basic-database.html#example-configuring-mysql) ), but maybe using the right configuration it is automatically performed somewhere (though I can't find where). This must be performed else every `pdnsutil` command in `powerdns-deployment.yaml` will fail.

Finally seems there are many values which could create problems if changed (for example the pvc just takes care of `powerdns.mysql_user` ignoring the `admin.mysql_user` value), but this is just for info, not really important.

Monday I will try to perform these change, but I would like to know if I am wrong.

Thank you
